apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n66cg21kg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n66cg21kg-go 
  name: n66cg21kg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n66cg21kg-go 
